### ISSUE TITLE
Allow services to emulate/impersonate user (send with username)

### ISSUE THREAD

**Issue by ildar** [matrix-org/matrix-appservice-gitter#103] opened 2020-10-26 05:05 UTC
Gitter seem to finish their part of the job of replacing `matrixbot` with something user-name contained: https://gitlab.com/gitlab-org/gitter/webapp/-/issues/1076
When our bridge would start using the feature?

**Comment by auscompgeek** [comment] 2020-11-21 05:49
Duplicate of #31

**Closed as completed** 2020-11-23 11:20 UTC
